### PR TITLE
First steps towards dockerization

### PR DESCRIPTION
**Pull request by StoneCypher**
This follows a slightly modified set of your installation instructions to create a pair of images - the standard 5.1 gig CUDA image, and a novel 14.6g image containing progrockdiffusion.

This isn't particularly useful yet.  You can go inside the container and generate an image, but it's just command line, and there's no way to export the image from the container yet (you can view it with cacaview, srsly, to confirm that it works.)

I will follow this up with something more usable soon, but I want to get some hooves on the ground.

This does *not* use Anaconda.  I tried, buddy; really I did.  [The conflict was so large that my terminal only retained the last 32k of it](https://gist.github.com/StoneCypher/364e92264018815473418658d631dedd), and none of the IRC channels or discords I tried could help.

So I just ditched Anaconda, because as far as I could tell, it was only being used to install opencv and to make a venv, and venvs don't matter in a docker container.

Later, I will set up a binding so that there's a folder in-machine which is also exported, and make a neato little web UI that doesn't feel like that colab.  I just, y'know, haven't, yet.

### CODE REVIEW

**Comment by roma-glushko** [comment]
@lowfuel yes, seems like my PR could greatly simplify the current docker file

**Comment by StoneCypher** [comment]
Basically just if you think this will be useful then merge it, then I'll update to @roma-glushko 's stuff once his `requirements.txt` stuff is merged and the instructions are updated, then I'll send another PR once I have a frontispiece for it

**Comment by StoneCypher** [comment]
The reason that I think that this is useful is that it makes deploying into cloud hosting *much* easier and also makes running this on a machine that has to be set up some other way for some other project practical

**Comment by StoneCypher** [comment]
at the end, if you adopt both roma's and my suggestions, you will have four install paths, two of them one-liners and two of them nearly so

1. local, gpu
2. local, cpu
3. dockerized, gpu
4. dockerized, cpu

**Comment by StoneCypher** [comment]
The other reason that it's probably good to get this merged earlier rather than later is that sooner or later someone else will want this too, and redo the work.  And honestly, it's a slog.

I'd rather they inherit my already finished one, and donate their "hey dummy that's not how docker works" to me, than have wasted parallel effort.

Almost all cloud ML is done in docker containers, y'know?  Might as well get ready.

**Pull request merged**
