### PR TITLE
#9 Moved all repositories and dependencies under pip control

### PR DESCRIPTION
**Pull request by roma-glushko**
The main changes include:

- Moved all repositories and dependencies under pip control
- Updated the readme.md fle
- ignored popular IDE files

### CODE REVIEW

**Comment by roma-glushko** [comment]
@lowfuel this is what I mean by simplifying the installation process. What do you think?

**Comment by lowfuel** [comment]
> @lowfuel this is what I mean by simplifying the installation process. What do you think?

Very cool! Let me try it out before merging it in though! Also it says there's a conflict with README.md (I'm guessing I changed something after you forked - was removing the SLIP stuff).

**Comment by roma-glushko** [comment]
@roma-glushko Yeah, I would appreciate if you could check that on your side 🙏  The conflict is not a problem. I can resolve them

**Comment by lowfuel** [comment]
> @roma-glushko Yeah, I would appreciate if you could check that on your side 🙏 The conflict is not a problem. I can resolve them

Okay - I just tried to fix the conflict,  haven't done that before so hopefully I did it right. :)
Anyway I will try this out today and let you know how it goes.

**Comment by roma-glushko** [comment]
@lowfuel cool, thank you 🚀 Let me know if there is anything to address

**Comment by lowfuel** [comment]
> @lowfuel cool, thank you 🚀 Let me know if there is anything to address

Not sure if you saw my other message, but I tried it and found it still needs ResizeRight and the OpenCV installation. By the way, I noticed in the dockerfile someone created that they're installing opencv from pip instead of conda (in fact they aren't using conda at all). I wonder if we should move to those approaches for manual setup, and just leave conda for people who know what they're doing and want venvs. Thoughts? It would simplify things even more I assume.

**Comment by roma-glushko** [comment]
@lowfuel let me try to fix the issues today

>  I wonder if we should move to those approaches for manual setup, and just leave conda for people who know what they're doing and want venvs. Thoughts? It would simplify things even more I assume.

Yes, conda is compatible with pip's requirements.txt files and popular in some science-related circles. A lot of people use plain pip as a dependency installer. So I would not take any "opinioned" approaches and leave this part to our users.

**Comment by roma-glushko** [comment]
@lowfuel Have taken a look the issue you had found. Turned out I missed those two deps, so I have installed a headless version of OpenCV via pip. The situation is a bit trickier with ResizeRight as it's not a python module but just a  few python files which we could not technically require as a common deps. So I have leveraged git submodules in order to pull that code as well.

**Comment by lowfuel** [comment]
> @lowfuel Have taken a look the issue you had found. Turned out I missed those two deps, so I have installed a headless version of OpenCV via pip. The situation is a bit trickier with ResizeRight as it's not a python module but just a few python files which we could not technically require as a common deps. So I have leveraged git submodules in order to pull that code as well.

Thanks for looking into that. I'm trying again to go through the instructions and found some more problems (did you try it? I hope this isn't just me).

Torch doesn't install because:
```
ERROR: Could not find a version that satisfies the requirement torch==1.10.2+cu113
```
This happens if I try to manually run the pip command that I believe your requirements file generates:
```
pip install torch==1.10.2+cu113
```
But if I add the -f URL (as per the old instructions), it is able to find it and install it:
```
pip install torch==1.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```
Can the URL be added in the requirements.txt or does it not work when coming in that way?

The same happens for torchvision and torchaudio.

In addition, I had to treat CLIP, guided-diffusion, taming-transformers, and latent-diffusion the same way as ResizeRight, manually cloning into the PRD directory. So I think the same thing you did for ResizeRight needs to be done for those as well. To be honest I think this is due to the somewhat sloppy way Disco's code incorporates them, but I'm reluctant to fiddle too much there.

**Comment by lowfuel** [comment]
FYI @roma-glushko I added a new branch called simpleinstall. If you want to work directly in there on the requirements files, that'd be great. I've added the current versions so it, and have been working on streamlining the installation instructions too.

**Comment by lowfuel** [comment]
Also @roma-glushko I fixed up the other issues and it all seems to be working now (on linux at least, will test the others as well). I will close this pull request and merge everything in from the simpleinstall branch instead.

Thanks again for the help on this!

**Pull request closed without merging**
