### PR TITLE
Simple GUI to edit settings, run, and view progress.

### PR DESCRIPTION
**Pull request by KnoBuddy**
Should just work out of the box. I know the code is an absolute mess, and the features are lacking, but honestly it already does everything I needed it to do. 

Open to suggestions, ideas, etc.

image

### CODE REVIEW

**Comment by lowfuel** [comment]
Looking good. I would probably have it use a temporary settings filename rather than overwriting settings.json though.

**Comment by KnoBuddy** [comment]
Cleaned up the layout a bit and it now imports from gui_settings.json if found, if not imports from settings.json but will not overwrite.

**Comment by KnoBuddy** [comment]
Cleaned up some more, added checkboxes.
image

**Comment by KnoBuddy** [comment]
image

**Comment by KnoBuddy** [comment]
Added checkboxes and support for multiple prompts

image

**Comment by KnoBuddy** [comment]
The default settings.json file has comments at the top that breaks the json parser in python, which leaves 3 options:

1: Remove the comments from the top of the settings.json file
2: Install a library and parse the comments out
3: Create a default copy of settings.json named gui_settings.json as an addition file to the repo.

Let me know which you'd like to do and I'll implement it. Otherwise, I would like to open it up to bug testing. I think I'm done with this and unless anyone else has something to add, we can go ahead and merge.

**Comment by lowfuel** [comment]
I think you just need to import json5, which we already require for prd.py so people should have it. Then it can parse json files with comments.
`import json5 as json`

**Comment by KnoBuddy** [comment]
Works flawlessly.

**Comment by lowfuel** [comment]
Nice! Looking forward to trying it. Is the change to the install instructions for pytorch needed for this to work?

**Comment by KnoBuddy** [comment]
No, but the change was required for me to get it to work on my windows desktop which is where I did the majority of the development.

**Comment by lowfuel** [comment]
Okay, well do me one last favor if you don't mind? Let's keep the README the same for now. I will be happy to change it separately once I test a fresh install with your conda method, but I don't want to tie incorporating the gui with testing a different pytorch install method (for most people the current method works -- not to say yours doesn't, just that I want to thoroughly test it before I make that change).

**Comment by KnoBuddy** [comment]
Done.

**Pull request merged**
